### ISSUE TITLE
BRANDING - Can't add custom domain

### ISSUE THREAD

**Issue by Agora-Issues** [lumosoft-co/Agora-Issues#25]
I try to add my domain (shop.bownet.xyz) as the shop URL. I made the CNAME record on Namecheap, waited a while, and I can't add it. It lets me add the domain, but then just doesn't save (the field is empty after refreshing) and the website shows a 404 when I go to it. Everything else saves, just not that. I made sure to disable my adblocker, still doesn't work. I'm using Microsoft Edge on Windows 11. 

 account: bowfun@bownet.xyz

**Comment by bow-official** [comment]
Namecheap auto-adds a dot there, even if I try removing it. Hopefully that isn't causing this.
![image](https://github.com/lumosoft-co/Agora-Issues/assets/89054289/f20475ea-f3bd-4862-9261-647b7a5e1654)

**Comment by bow-official** [comment]
Now it shows the text "shop has no theme" on the website, but the theme works fine on the other URL.

**Comment by jtsus** [comment]
This issue has been verified as fixed, can you check to see if it works for you now?

**Comment by bow-official** [comment]
![image](https://github.com/lumosoft-co/Agora-Issues/assets/89054289/d6d97330-e2f9-4c00-8a76-19238e1d1d4f)
I get this now, even though it is pointed correctly in the DNS and has been for around 24 hours.

**Comment by jtsus** [comment]
Seems like you hit a rate limit with the certificate creation, you can try again in around 12 hours.

**Comment by bow-official** [comment]
Okay, it's fixed now.
